 name: Deploy to Production
 
 on:
   push:
     branches:
       - release

 jobs:
   deploy:
     name: Build, Deploy to S3 bucket
     runs-on: [ubuntu-latest]

     strategy:
       matrix:
         node-version: [12.16.x]

     steps:
       - uses: actions/checkout@v2

       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v1
         with:
           node-version: ${{ matrix.node-version }}

       - name: Npm install
         run: npm install

       - name: Build
         run: npm run build --prod
         env:
          CI: ""

       - name: Transfer to S3 for serving static
         uses: jakejarvis/s3-sync-action@master
         with:
           args: --acl public-read --follow-symlinks --delete
         env:
           AWS_S3_BUCKET: joraengdahaeng
           AWS_ACCESS_KEY_ID: ${{ secrets. IAM_ACCESS_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.IAM_ACCESS_SECRET_KEY }}
           AWS_REGION: 'ap-northeast-2'
           SOURCE_DIR: 'dist'
